# Site settings
title: Patience, Young Grasshopper
header-img: img/home-bg.png
email: lcbaz15@gmail.com
copyright_name: lcbaz15
description: > # this means to ignore newlines until "baseurl:"
  Learning and Living the Dream
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lcbaz15
learn_profile: lcbaz15
email_username: lcbaz15@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
